input RegistrationInput{
  name: String!
  email: String!
  password: String!
  confirmPassword: String!
}

input LoginInput{
  email: String!
  password: String!
}

type User{
  id: ID!
  name: String!
  email: String!
  joined: String!
}

input LocationInput {
  lat: Float!
  lon: Float!
  distanceLimit: Int!
}

type Location {
  lat: Float
  lon: Float
}

input ApartmentInput{
  rooms: Int!
  city: String!
  country: String!
  lat: Float
  lon: Float
}

type Apartment{
  id: ID!
  rooms: Int!
  city: String!
  country: String!
  userId: ID!
  location: Location!
  distance: String
}

input SearchInput {
  rooms: Int
  city: String
  country: String
}

type FavoriteList{
  favorites: [Apartment]
}

type Query {
  """ search apartment using filter and location coordinates """
  search(filter: SearchInput, location: LocationInput): [Apartment]
  """ shows user's favorite apartments list """
  favoriteList: FavoriteList
}

type Mutation {
  # register new user
  registration(input: RegistrationInput!): User
  # login using email & password
  login(input: LoginInput!): String

  # create new apartment entry connected to user
  createApartment(input: ApartmentInput!): Apartment
  # for development use
  removeApartment(id: ID!): Boolean

  # add/remove favorite to/from user favorite list. return operation message
  toggleFavorite(id: ID!): String
}