type Customer {
  name: String!
  email: String!
  phone: String!
}

input CustomerInput {
  name: String!
  email: String!
  phone: String!
}

type Vehicle {
  make: String!
  model: String!
  vin: String!
}

input VehicleInput {
  make: String!
  model: String!
  vin: String!
}

type Booking {
  id: ID!
  dateTime: String!
  vehicle: Vehicle!
  customer: Customer!
}

input BookTimeInput {
  date: String!
  time: Int!
}

input BookingInput {
  customer: CustomerInput!
  vehicle: VehicleInput!
  booking: BookTimeInput!
}

input SearchInput {
  date: String
  vin: String
}

type Query {
  """
    search apartment using filter and location coordinates
  """
  getBooking(filter: SearchInput): [Booking]
}

type Mutation {
  """
    create new booking
  """
  createBooking(input: BookingInput!): Booking
}
